server:
  port: 1004
  
spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
        
fw:
  auth:
    clientId: ENC(eZLNwFxeSKENBh1pu/M/rMMB76nxo/RLhWSaSLHa8+0=)
    clientSecret: ENC(sKbpJGHz9JZmdydv1WOyAYjyXm2irxc0xYqvQ6VpF31uEw/FVNxYeA==)
    scope: server

urls:
  collects:
    - /auth/**
    - /**/*.css
    - /**/*.png
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token

logging:
  config: classpath:logback.xml