FROM java:8
MAINTAINER fw-cloud-framework <liuweijw.github@foxmail.com>

ADD ./cloud-admin/fw-cloud-business-adminitor.jar /app/

CMD ["java", "-Xmx300m", "-jar", "/app/fw-cloud-business-adminitor.jar"]

EXPOSE 2002
